version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d

    ports:
      - "1337:1337"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:1337/${POSTGRES_DB}
    ports:
      - "3000:3000"

volumes:
  pgdata:
